version: "3.8"

name: hgraber

services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BINARY_PATH: _build/hgraber-docker-server
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
    command: --fs-token fs-local --fs-addr file:8080 --ws-token=local-debug --ag-addr :8081 --ag-token agent-token
    depends_on:
      - file
      - postgres
    environment:
      PG_SOURCE: postgres://hguser:hgpass@postgres:5432/hgdb?sslmode=disable

  file:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BINARY_PATH: _build/hgraber-docker-fileserver
    command: --token fs-local
    volumes:
      - file-loads:/app/loads
      - file-exported:/app/exported

  agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BINARY_PATH: _build/hgraber-docker-agent
    command: --token agent-token --addr server:8081 --name local-docker-debug
    depends_on:
      - server

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: hgpass
      POSTGRES_USER: hguser
      POSTGRES_DB: hgdb
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - :5432 


volumes:
  file-loads:
  file-exported:
  postgresql: